config/routes.rb
PrecisionGaming::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :posts
  resources :topics
  resources :players
  resources :casts

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/forum', :to => 'topics#index'
  match "/posts/new/:id" => "posts#new"
  
  get "users/new"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessible :name, :content

  
  has_many :posts, :dependent => :destroy

  validates :name,  :presence   => true,
                    :length     => {:maximum => 50},
                    :uniqueness => { :case_sensitive => false }
  validates :content, :presence   => true

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @important = Post.where(:topic_id => 1).limit(3)
    @event = Post.where(:topic_id => 2).limit(3)
    @cast = Post.where(:topic_id => 3).limit(3)
    @replay = Post.where(:topic_id => 4).limit(3)
    @other = Post.where(:topic_id => 5).limit(3)
  end
  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.paginate(:page => params[:page],:per_page => 10)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<div onclick="location.href='<%= topic_path(1) %>'" style="cursor: pointer" >
<h1>Important</h1>
</div>
  <table class="posts" summary="Important posts">
    <%= render @important %>
  </table>
<div onclick="location.href='<%= topic_path(2) %>'" style="cursor: pointer" >
<h1>Events</h1>
</div>
  <table class="posts" summary="Event posts">
    <%= render @event %>
  </table>
<div onclick="location.href='<%= topic_path(3) %>'" style="cursor: pointer" >
<h1>Casts</h1>
</div>
  <table class="posts" summary="Casts posts">
    <%= render @cast %>
  </table>
<div onclick="location.href='<%= topic_path(4) %>'" style="cursor: pointer" >
<h1>Replays</h1>
</div>
  <table class="posts" summary="Replays posts">
    <%= render @replay %>
  </table>
<div onclick="location.href='<%= topic_path(5) %>'" style="cursor: pointer" >
<h1>Others</h1>
</div>
  <table class="posts" summary="Others posts">
    <%= render @other %>
  </table>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<p><%= @topic.content %></p>
  <table class="posts" summary="Important posts">
    <%= render @posts %>
  </table>
<%= will_paginate @posts %>

<%= link_to "Create new post", :controller => "posts", :action => "new", :id => @topic.id %>