config/routes.rb
PrecisionGaming::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :posts
  resources :topics
  resources :players
  resources :casts

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/forum', :to => 'topics#index'
  match "/posts/new/:id" => "posts#new"
  
  get "users/new"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="posts" summary="User posts">
    <%= render @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="post">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
    <%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => feed_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
    <%= f.hidden_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <% if @post.topic_id == 3 %>
      <div class="field">
        <%= f.label :winner_name %><br />
        <%= text_field_with_auto_complete :post,:winner_name,{},{:url => players_path(:js), :method => :get, :param_name => 'search' }%>
      </div>
      <div class="field">
        <%= f.label :winner_race %><br />
        <%= f.select(:winner_race, [['Protoss', 1], ['Terran', 2], ['Zerg',3]]) %>
      </div>
      <div class="field">
        <%= f.label :loser_name %><br />
        <%= text_field_with_auto_complete :post,:loser_name,{},:url => players_path(:js), :method => :get, :param_name => 'search'%>
      </div>
      <div class="field">
        <%= f.label :loser_race %><br />
        <%= f.select(:loser_race, [['Protoss', 1], ['Terran', 2], ['Zerg',3]]) %>
      </div>
      <div class="field">
        <%= f.label :game_type %><br />
        <%= f.select(:game_type, [['1 vs 1', '1 vs 1'], ['2 vs 2', '2 vs 2'], ['3 vs 3','3 vs 3'],['4 vs 4','4 vs 4']]) %>
      </div>
      <div class="field">
        <%= f.label :link %><br />
        http://www.youtube.com/watch?v=<b>dQw4w9WgXcQ</b><br />
        <%=  f.text_field :link%>
      </div>
    <% end %>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
    <%= f.hidden_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="posts">
      <%= pluralize(current_user.posts.count, "post") %>
    </span>
  </a>
</div>