config/routes.rb
PrecisionGaming::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :posts
  resources :topics
  resources :players
  resources :casts

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/forum', :to => 'topics#index'
  match "/posts/new/:id" => "posts#new"
  
  get "users/new"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/models/cast.rb
class Cast < Post
  attr_accessible :link

  belongs_to :winner, :class_name => "Player", :foreign_key => "winner_id"

  belongs_to :loser, :class_name => "Player", :foreign_key => "loser_id"

  def winner_name
    Player.find(self.winner_id).name if self.winner_id
  end

  def winner_name=(name)
    self.winner_id = Player.find_or_create_by_name(name).id unless name.blank?
  end

  def loser_name
    Player.find(self.loser_id).name if self.loser_id
  end

  def loser_name=(name)
    self.loser_id = Player.find_or_create_by_name(name).id unless name.blank?
  end


  #validates :winner_id, :presence => true
  #validates :loser_id, :presence => true
  validates :link, :presence => true
  validates :winner_name, :presence => true
  validates :loser_name, :presence => true
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_filter :authenticate
  before_filter :authorized_user, :only => :destroy

  def new
    @post = Cast.new
    @post.topic_id = params[:id]
  end

  def show
    @cast = Cast.find(params[:id])
    @microposts = @cast.microposts.paginate(:page => params[:page],:per_page => 10)
    @micropost = Micropost.new
    @micropost.post_id = @cast.id
  end

  def create
    Post
    @post = Cast.new(params[:cast])
    @post.user = current_user

    @post.winner_name = params[:post][:winner_name]
    @post.loser_name = params[:post][:loser_name]


    if @post.save
      #if ! winner = Player.where("name = ?", @post.winner_name).first
      #  winner = Player.create!(:name => @post.winner_name)
      #end
      #@post.winner_id = winner.id
      #if ! loser = Player.where("name = ?", @post.loser_name).first
      #  loser = Player.create!(:name => @post.loser_name)
      #end
      #@post.loser_id = loser.id
      flash[:success] = "Cast created!"
      redirect_to topic_path(@post.topic_id)
    else
      puts params[:cast][:topic_id]
      render :controller => "posts", :action => "new", :id => params[:cast][:topic_id]
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted!"
    redirect_back_or root_path
  end
  
  private

    def authorized_user
      @post = current_user.posts.find_by_id(params[:id])
      redirect_to root_path if @post.nil?
    end
  
end

app/views/casts/_cast.html.erb
<tr>
  <td>
    <div onclick="location.href='<%= cast_path(cast) %>'" style="cursor: pointer" >
  <%= link_to cast.winner.name, cast.winner %><br/>
  <% if cast.winner_race == 1 then%>
    <%= image_tag('Protoss_2.png', :size => "100x100" ) %>
  <% elsif cast.winner_race == 2 then%>
    <%= image_tag('Terran_2.png', :size => "100x100") %>
  <% elsif cast.winner_race == 3 then%>
    <%= image_tag('Zerg_2.png', :size => "100x100") %>
  <% end %>
    </div>
  </td>
  <td>
    <%= image_tag('vs_icon.jpg') %>
  </td>
  <td>
    <div onclick="location.href='<%= cast_path(cast) %>'" style="cursor: pointer" >
  <%= link_to cast.loser.name, cast.loser %><br/>
  <% if cast.loser_race == 1 then%>
    <%= image_tag('Protoss_2.png', :size => "100x100" ) %>
  <% elsif cast.loser_race == 2 then%>
    <%= image_tag('Terran_2.png', :size => "100x100") %>
  <% elsif cast.loser_race == 3 then%>
    <%= image_tag('Zerg_2.png', :size => "100x100") %>
  <% end %>
    </div>
  </td>

  <% user = cast.user rescue User.find(cast.user_id)%>
  <td class="post" >
    <div onclick="location.href='<%= cast_path(cast) %>'" style="cursor: pointer" >
    <span class="title"><%= link_to cast.winner.name, cast.winner %> Vs. <%= link_to cast.loser.name, cast.loser %></span><br/>
    <span class="content"><%= cast.content %></span>
    <span class="timestamp">
      Posted by <%= link_to user.name, user %> <%= time_ago_in_words(cast.created_at) %> ago.
    </span>
</div>
  </td>
  <% if current_user?(cast.user) %>
  <td>
    <%= link_to "delete", cast, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => cast.content %>
  </td>
  <% end %>
</tr>

app/views/casts/new.html.erb
<h1><%= @post.topic.name %></h1>
<%= render 'shared/post_form' %>

app/views/casts/show.html.erb
<h1><%= link_to @cast.winner.name, @cast.winner %> Vs. <%= link_to @cast.loser.name, @cast.loser %></h1>

<span class="content"><%= @cast.content %></span><br/>
<% user = @cast.user rescue User.find(@cast.user_id)%>
<span class="timestamp">
  Posted by <%= link_to user.name, user %> <%= time_ago_in_words(@cast.created_at) %> ago.
</span>

<iframe title="YouTube video player" width="480" height="390" src="http://www.youtube.com/embed/<%= @cast.link %>" frameborder="0" allowfullscreen></iframe>

<table>
  <tr>
  <%= render @microposts %>
  </tr>
</table>
<%= will_paginate @microposts %>
<%= render 'shared/micropost_form' %>